version: "3.1"
services:

  picpay-mysql:
    image: mysql:5.6
    container_name: picpay-mysql
    working_dir: /application
    volumes:
        - ./database/files:/var/lib/mysql
        - ./database/conf:/etc/mysql/conf.d
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=picpay
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
    ports:
        - "3307:3306"
    networks:
      picpay_api_net:
        ipv4_address: 172.28.1.1

  picpay-webserver:
    image: nginx:alpine
    container_name: picpay-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    links:
      - picpay-php-fpm
    networks:
      picpay_api_net:
        ipv4_address: 172.28.1.2

  picpay-php-fpm:
    build: phpdocker/php-fpm
    container_name: picpay-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
    links:
      - picpay-mysql
    networks:
      picpay_api_net:
        ipv4_address: 172.28.1.3

  picpay-transaction-service:
    image: nginx:alpine
    container_name: picpay-transaction-service
    working_dir: /application
    volumes:
      - ./transaction_service:/application
      - ./phpdocker/transaction-service-nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8001:80"
    links:
      - transaction-service-php-fpm
    networks:
      picpay_api_net:
        ipv4_address: 172.28.1.4

  transaction-service-php-fpm:
    build: phpdocker/transaction-service-php-fpm
    container_name: transaction-service-php-fpm
    working_dir: /application
    volumes:
      - ./transaction_service:/application
      - ./phpdocker/transaction-service-php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
    networks:
      picpay_api_net:
        ipv4_address: 172.28.1.5

networks:
  picpay_api_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16